language: ruby
rvm:
- 2.2.0
notifications:
  email:
    recipients: front-end@bq.com
    on_success: change
    on_failure: never
before_install:
- npm install -g bower
- gem install bundler
install:
- bower install
- bundle install
script:
- bundle exec jekyll build
- bash ./travis-runner.sh
branches:
  only:
  - master
env:
  global:
    secure: Jv4rbaTWg2mi23NZsiLfp34F23o0EVUGTdLv2qVcKt5AbZzi1IpeXhs6olTCrpyO+DxLTfKFbwGwL20myr7Tf94uHE/PM3+HYocSxTjiiOK8Mvj7FF75TCXRVUnx135jd36BthihEaAZZmOU4/xYtARXRU0i/JyPZXUiNM0Yvhc=
