language: ruby
rvm:
- 2.2.0
notifications:
  email:
    recipients: front-end@bq.com
    on_success: change
    on_failure: never
before_install:
- npm install -g bower
- gem install bundler
install:
- bower install
- bundle install
script:
- bundle exec jekyll build
- bash ./travis-runner.sh
branches:
  only:
  - master
env:
  global:
	# GH_OAUTH_TOKEN is the oauth token generated as described at
	# https://help.github.com/articles/creating-an-oauth-token-for-command-line-use
	#
	# curl -u 'username' -d '{"scopes":["repo"],"note":"push to gh-pages from travis"}' https://api.github.com/authorizations
	#
	# It must be encrypted using the travis gem
	# http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
	#
	# travis encrypt GH_OAUTH_TOKEN=XXXXXXXXXXXXXXX
	#
	# User specific env variables  
    - secure: 'D/s+DNENn9UK0IIthxT0eIk9PSpk2Rcufz5eXl/MES7LY6z6gR32GeT1NsYJA8y09Kp29PM4gA0aJ2mIbQupjRT993WhwMycVBxnBNv8mpblCDV9FPN849mwWVrybwJ50pWSN0fZcS9bvx57OUf7yE85GGEgPBOFgg88K/pMno4='
    - GH_OWNER: bq
    - GH_PROJECT_NAME: penguin-doc